server:
  port: 8001

spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rm-wz9ep065eb7v0h5r2wo.mysql.rds.aliyuncs.com:3306/springcloud2020?characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
    username: srcb
    password: Xdsjsd1510
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT1FROMDUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      filter:
        slf4j:
          enabled: true
          statement-create-after-log-enabled: false
          statement-close-after-log-enabled: false
          result-set-open-after-log-enabled: false
          result-set-close-after-log-enabled: false
          result-set-log-enabled: false
mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.xds.springcloud.entitys
eureka:
  instance:
    hostname: localhost # eureka 服务器的实例名称
    instance-id: payment8001
    prefer-ip-address: true
  client:
    # 表示是否将自己注册进入Eureka，默认为true
    register-with-eureka: true
    # 是否从EurekaServer抓取已有的注册信息，默认为true.单节点无所谓，集群必须设置为true,才能配合Ribbon使用负载均衡
    fetch-registry: true
    service-url:
      # 设置Eureka Server 交互的地址查询服务和注册服务都需要依赖这个地址
#      defaultZone: http://${eureka.instance.hostname}:7001/eureka/
       defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
logging:
  config: classpath:logback-spring.xml



